name: nohfibu
description: nohkumados Finanz Buchhaltungs App

  very simple fincnacial account library to implement a simple, filebased, 
  double-entry accounting.
  account plan and associated journali are stored in a csv file,
  then validation of the journal with the plan, and computation of the financial 
  analysis can be achieved with it.
#publish_to: https://pub.dev

version: 0.0.2-alpha
homepage: https://www.nohkumado.eu/nohfibu/ 
repository: https://github.com/nohkumado/dart_fibu

executables:
  wbconvert:
  nohfibu:


environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  args: ^2.3.0
  intl: ^0.17.0
  sprintf: ^6.0.0
  csv: ^5.0.0

dev_dependencies:
   test: '>=1.15.0 <2.0.0'
