name: nohfibu
description: nohkumados Finanz Buchhaltungs App

  very simple financial account library to implement a simple, filebased, 
  double-entry accounting. 
  Fast ops allow prepared statements.
#publish_to: https://pub.dev

version: 0.0.3
homepage: https://www.nohkumado.eu/nohfibu/ 
repository: https://github.com/nohkumado/dart_fibu

executables:
  wbconvert:
  nohfibu:


environment:
  sdk: '>=2.12.0 <3.0.0'


dependencies:
  args: ^2.3.1
  intl: ^0.17.0
  sprintf: ^6.0.0
  csv: ^5.0.1
  expressions: ^0.2.4
  posix: ^3.1.0

dev_dependencies:
   test: '>=1.15.0 <2.0.0'
