name: nohfibu
description: nohkumados Finanz Buchhaltungs App

  very simple financial account library to implement a simple, filebased, 
  double-entry accounting. 
  Fast ops allow prepared statements.
#publish_to: https://pub.dev

version: 0.0.4
homepage: https://www.nohkumado.eu/nohfibu/ 
repository: https://github.com/nohkumado/dart_fibu

executables:
  wbconvert:
  nohfibu:


environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  args: ^2.5.0
  intl: ^0.19.0
  sprintf: ^7.0.0
  csv: ^6.0.0
  expressions: ^0.2.5+1
  posix: ^6.0.1
  git: ^2.3.0

  path: any
dev_dependencies:
   test: '>=1.15.0 <2.0.0'
