name: nohfibu
description: nohkumados Finanz Buchhaltungs App

  very simple financial account library to implement a simple, filebased, 
  double-entry accounting. 
  Fast ops allow prepared statements.
#publish_to: https://pub.dev

version: 0.2.0
homepage: https://www.nohkumado.eu/nohfibu/ 
repository: https://github.com/nohkumado/dart_fibu

executables:
  wbconvert:
  nohfibu:
  facture:
  ledger:


environment:
  sdk: ">=3.0.0 <4.0.0"


dependencies:
  args: ^2.5.0
  intl: ^0.20.3
  sprintf: ^7.0.0
  csv: ^8.0.0
  expressions: ^0.2.5+1
  posix: ^6.0.1
  git: ^2.3.0
  path: ^1.9.1
  pdf: ^3.13.1
  yaml: ^3.1.4
  crypto: ^3.0.7
  cryptography: ^2.9.0
  qr: ^3.0.2

dev_dependencies:
   test: '>=1.15.0 <2.0.0'
